[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
